---
- hosts: webservers
  gather_facts: false

  become: true
  remote_user: ubuntu

  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
    - env_vars/{{ env }}-vault.yml

  pre_tasks:
    - name: Update apt repositories
      apt:
        update_cache: true

  roles:
    - database
    - cdriehuys.django-app
    - cdriehuys.nginx
    - letsencrypt
