---
language: python
python: 3.4

cache: pip

env:
  global:
    # Don't run tests in parallel. This fixes an issue with code coverage.
    - PYTEST_ADDOPTS="-n0"

install:
  - pip install --upgrade pip
  - pip install -r requirements/test.txt
  - pip install codecov

script:
  - flake8
  - coverage run -m pytest km_api/

after_success: codecov


notifications:
  email:
    on_failure: always
    on_success: never
