---
language: python
python: 3.4

cache: pip

env:
  global:
    # Don't run tests in parallel. This fixes an issue with code coverage.
    - PYTEST_ADDOPTS="-n0"

install:
  - pip install --upgrade pip
  - pip install -r requirements/test.txt
  - pip install codecov

script:
  - flake8
  - COVERAGE_FILE=.coverage.unit coverage run -m pytest -m "not integration" km_api/
  - COVERAGE_FILE=.coverage.int coverage run -m pytest -m "integration" km_api/

after_success:
  - coverage combine
  - codecov


notifications:
  email:
    on_failure: always
    on_success: never
