language: python
python: 3.6

cache: pip

install:
  - pip install --upgrade pip
  - pip install -r requirements/test.txt
  - pip install codecov

before_script: flake8

script: coverage run -m pytest km_api/

after_success: codecov
