language: python
python: 3.4

cache: pip

env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAIR3ALLAIYVISFBZQ
    - AWS_APP_NAME=km-api
    - AWS_BUCKET_NAME=elasticbeanstalk-us-east-1-656952694364
    - AWS_REGION=us-east-1
    - secure: "YARJiZmaMEM18Be1h8AUtB7xl9mK/Fcvm6FR8BTrQuNv9xRrLzlJ2Lhsl6+RpP/ifX72CUbXubwIX6h0KDgZriVE3SV/jQ0Ium6jQRbhnkTYE7xrE1FgTJIRhdDnNMD3Qhy7EEFROYkLXmiVf3wDA24twn7ez/8W/In6rIJkt48yGLxeGcPMq/7xCiXg0pyWOiibiZKzxHyFpqW37XZLsynjMTrX75FXEiVifmp6Pc0UVu7TbcOLQxS1by/HT/EbMYzLZJmJCwdP/Kq7rCfc4AMpacFJJQQuQH7GhQikdxd1priiqqtFYGeAKXRXKjTAr0iR4Pr95exo9GKysBox8mvfPFHJmwmBYrlhazIUkUeZOhj0IigOHjDMn/vNS/4vHI0ZDuecJvSHD8CmpmNcy8yPXHT/ywyQy/KlA10YkaFrFqFB5kLIqFZaARyJ9MDoP7bjkGU46ArJmcR14OIjAER+39S9jwaXtSFCmKn4+M7jyawe5Pm3O6meSHK6dGMj+rPPbH6VIpKZjxo4gT19EIt7tCy0l26pJDGNT3LtbTp48mSZTCnVmufFYuHgB1dEu77Jsxca++Non8rG1R9LegY/VH7h/CZMACsa/wsxiQM4U81x/Zg5HHOZanH7t/MjaxZUBanRXWA95N6JMfJL5bd/2ChCeHJT61IN8nDLhDU="

install:
  - pip install --upgrade pip
  - pip install -r requirements/test.txt
  - pip install codecov

script:
  - coverage run -m pytest km_api/
  - flake8

after_success: codecov

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_REGION
    app: $AWS_APP_NAME
    env: km-api-dev
    bucket_name: $AWS_BUCKET_NAME
    skip_cleanup: yes
    on:
      branch: develop

  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_REGION
    app: $AWS_APP_NAME
    env: km-api
    bucket_name: $AWS_BUCKET_NAME
    skip_cleanup: yes
    on:
      tags: yes

notifications:
  slack:
    on_failure: always
    on_success: change
    rooms:
      - secure: "HluqptJoQM+rR6s8FwcP47KME/78aAjeI8hLR1uvjdVo+X20jdbSACH4uo/DNoVeTrrpb6WlbnrZ3fKIyy06hLhBo8luTykn/fB+T+2+e+N6XQVpGrIMeNMjNNr0p8sggcpscaf8rMa1oi2qqyXLQavxBqjw/mjje2aZ64BVWxi4NxRIs4lksKnGDMQzU/dR4g04tMxgP5By4mWq0PA/fdbT5buaZLfTdtdVYeOWrZR7PGILq2hRVHkTigTmiFf3+F8jxLe2nFopUaMqEEXAA56lSgI4vhU+crsnEpbBLdiJAB9yF/1BDi3aJI3yibey+7d3qtfS8yBj1RoMy93Ia3biVDdc3sD7/1kzv5/kuuXRrmT/HBPWwk9pDLed8g7zKLSpIfqpIvczNZbSI5+UV6/G7hdRrc4dvppsG9cmhieZSUzMMpQ+VxgkwjxjdrjQsxsFeOPhi2bIwE256dO1DqVHUsP6IV/P2aIyfHodM1k91EvGUK0S1bNx9sVYd5+WicUqpTHDaJbWPRFOx8PlE+y7HvddOxeq1vTNtxOEBRHpiYl9wP8kQPwGjXkKDetp/xd8HCAXU95INCG9TBAYBrzxw6fh8gDqoAMpGUheF/22r5WE1wTxL5LPO4BB+j3pqJNmpcicYBH6bhgF0tJjHaEKQ6LjCt6daWLvLbY9hs4="
