language: python
python: 3.6

cache: pip

env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAIR3ALLAIYVISFBZQ
    - AWS_APP_NAME=km-api
    - AWS_BUCKET_NAME=elasticbeanstalk-us-east-1-656952694364
    - AWS_REGION=us-east-1
    - secure: "YARJiZmaMEM18Be1h8AUtB7xl9mK/Fcvm6FR8BTrQuNv9xRrLzlJ2Lhsl6+RpP/ifX72CUbXubwIX6h0KDgZriVE3SV/jQ0Ium6jQRbhnkTYE7xrE1FgTJIRhdDnNMD3Qhy7EEFROYkLXmiVf3wDA24twn7ez/8W/In6rIJkt48yGLxeGcPMq/7xCiXg0pyWOiibiZKzxHyFpqW37XZLsynjMTrX75FXEiVifmp6Pc0UVu7TbcOLQxS1by/HT/EbMYzLZJmJCwdP/Kq7rCfc4AMpacFJJQQuQH7GhQikdxd1priiqqtFYGeAKXRXKjTAr0iR4Pr95exo9GKysBox8mvfPFHJmwmBYrlhazIUkUeZOhj0IigOHjDMn/vNS/4vHI0ZDuecJvSHD8CmpmNcy8yPXHT/ywyQy/KlA10YkaFrFqFB5kLIqFZaARyJ9MDoP7bjkGU46ArJmcR14OIjAER+39S9jwaXtSFCmKn4+M7jyawe5Pm3O6meSHK6dGMj+rPPbH6VIpKZjxo4gT19EIt7tCy0l26pJDGNT3LtbTp48mSZTCnVmufFYuHgB1dEu77Jsxca++Non8rG1R9LegY/VH7h/CZMACsa/wsxiQM4U81x/Zg5HHOZanH7t/MjaxZUBanRXWA95N6JMfJL5bd/2ChCeHJT61IN8nDLhDU="

install:
  - pip install --upgrade pip
  - pip install -r requirements/test.txt
  - pip install codecov

before_script: flake8

script: coverage run -m pytest km_api/

after_success: codecov

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_REGION
    app: $AWS_APP_NAME
    env: km-api-dev
    bucket_name: $AWS_BUCKET_NAME
    skip_cleanup: yes
    on:
      branch: develop

  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_REGION
    app: $AWS_APP_NAME
    env: km-api
    bucket_name: $AWS_BUCKET_NAME
    skip_cleanup: yes
    on:
      tags: yes
