---
db_admin_username: dbadmin
db_admin_password: "{{ vault_db_admin_password }}"

db_username: django
db_password: "{{ vault_db_password }}"

db_map:
  kmapi:
    users:
      "{{ db_username }}": "{{ vault_db_password }}"


# Base AMIs off of Ubuntu 16.04
ami_builder_base: ami-9a0c088c
