# Generated by Django 2.0.3 on 2018-04-10 18:49

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0002_user_timestamps")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="A profile image for the user.",
                upload_to=account.models.get_user_image_path,
                verbose_name="profile image",
            ),
        )
    ]
