# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_emailaddress_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='user',
        ),
        migrations.AddField(
            model_name='emailconfirmation',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', related_query_name='confirmation', to='account.EmailAddress', verbose_name='email'),
        ),
    ]
