# Generated by Django 2.0.6 on 2018-06-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account", "0003_user_image")]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("created_at",),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        )
    ]
