# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='verified_action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'noop'), (2, 'replace primary email')], default=1, help_text='The action to perform after the email is verified.', verbose_name='verified action'),
        ),
    ]
