# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 21:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_emailaddress_verified_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', related_query_name='password_reset', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
