# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', related_query_name='confirmation', to='account.EmailAddress', verbose_name='email'),
        ),
    ]
