# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170725_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pending',
            field=models.BooleanField(default=False, help_text='A pending user holds placeholder information until a user registers with the email address of the pending user.', verbose_name='is pending'),
        ),
    ]
