# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
    ]
