# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_non_unique_emailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
    ]
