# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_non_unique_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_pending',
        ),
    ]
