# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailchimpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_hash', models.CharField(max_length=32, verbose_name='subscriber hash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailchimp_users', related_query_name='mailchimp_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'MailChimp user',
                'verbose_name_plural': 'MailChimp users',
            },
        ),
    ]
