# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km_auth', '0001_create_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Users without a verified email address may not log in.', verbose_name='email verified'),
        ),
    ]
