---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # Default to dev environment
    env: dev

  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
    - env_vars/{{ env }}-vault.yml

  roles:
    - cdriehuys.rds-postgres
    - { role: cdriehuys.ami-builder, ami_builder_task: create }

- hosts: amibuilder
  gather_facts: no

  become_user: root
  remote_user: ubuntu

  pre_tasks:
    - name: Install python 2
      become: yes
      become_user: root
      remote_user: ubuntu
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
      until: output.rc == 0
      retries: 3
      delay: 1

- hosts: localhost
  connection: local

  vars:
    # Default to dev environment
    env: dev

  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
    - env_vars/{{ env }}-vault.yml

  roles:
    - { role: cdriehuys.ami-builder, ami_builder_task: finalize }
