---
- name: Install certbot dependencies
  apt:
    cache_valid_time: "{{ apt_cache_time }}"
    name: "{{ item }}"
  with_items: "{{ certbot_dependencies }}"

- name: Add certbot PPA
  apt_repository:
    repo: "{{ certbot_repo }}"

- name: Install certbot
  apt:
    cache_valid_time: "{{ apt_cache_time }}"
    name: python-certbot-nginx

- name: Create SSL certification
  shell: >
    certbot --nginx
    --non-interactive
    --agree-tos
    -m '{{ letsencrypt_email }}'
    --domains '{{ letsencrypt_domains | join(",") }}'
    --redirect

- name: Automate certificate renewal
  cron:
    job: certbot renew
    special_time: daily
