# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import know_me.profile.models
import permission_utils.model_mixins


class Migration(migrations.Migration):

    dependencies = [("profile", "0002_mediaresourcecategory")]

    operations = [
        migrations.CreateModel(
            name="MediaResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time that the resource was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The file to associate with the resource.",
                        upload_to=know_me.profile.models.get_media_resource_upload_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the resource.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time that the resource was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="The category that the resource belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_resources",
                        related_query_name="media_resource",
                        to="profile.MediaResourceCategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "km_user",
                    models.ForeignKey(
                        help_text="The Know Me user who owns the resource.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_resources",
                        related_query_name="media_resource",
                        to="know_me.KMUser",
                        verbose_name="Know Me user",
                    ),
                ),
            ],
            options={
                "verbose_name": "media resource",
                "verbose_name_plural": "media resources",
            },
            bases=(
                permission_utils.model_mixins.IsAuthenticatedMixin,
                models.Model,
            ),
        )
    ]
