# Generated by Django 2.0.3 on 2018-04-03 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("profile", "0007_profile_ordering")]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="profiletopic", order_with_respect_to="profile"
        )
    ]
