# Generated by Django 2.0.3 on 2018-04-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("profile", "0008_profiletopic_ordering")]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="profileitem", order_with_respect_to="topic"
        )
    ]
