# Generated by Django 2.0.3 on 2018-04-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_mediaresource_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaresource',
            name='cover_style',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='An integer that provides a hint for clients as to how to style the resource.'),
        ),
    ]
