# Generated by Django 2.0.3 on 2018-06-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("profile", "0011_mediaresource_cover_style")]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="listentry", order_with_respect_to="profile_item"
        )
    ]
