# Generated by Django 2.2 on 2019-04-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("profile", "0012_listentry_ordering")]

    operations = [
        migrations.RemoveField(model_name="mediaresource", name="category"),
        migrations.DeleteModel(name="MediaResourceCategory"),
    ]
