# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0001_create_profile_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='The default profile group is displayed initially.', verbose_name='is default')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', related_query_name='group', to='know_me.Profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'profile group',
                'verbose_name_plural': 'profile groups',
            },
        ),
    ]
