# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0004_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('text', models.TextField(blank=True, default='', verbose_name='text')),
                ('gallery_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_items', related_query_name='profile_item', to='know_me.GalleryItem', verbose_name='gallery item')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='know_me.ProfileRow', verbose_name='profile row')),
            ],
            options={
                'verbose_name': 'profile item',
                'verbose_name_plural': 'profile items',
            },
        ),
    ]
