# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import know_me.models
import permission_utils.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('know_me', '0005_profileitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=know_me.models.get_km_user_image_upload_path, verbose_name='image')),
                ('quote', models.TextField(blank=True, null=True, verbose_name='quote')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='km_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            bases=(permission_utils.model_mixins.IsAuthenticatedMixin, models.Model),
        ),
    ]
