# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0006_kmuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('profile_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_entries', related_query_name='list_entry', to='know_me.ProfileItem', verbose_name='profile item')),
            ],
            options={
                'verbose_name_plural': 'profile list entry',
                'verbose_name': 'profile list entry',
            },
        ),
    ]
