# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import know_me.models
import permission_utils.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0006_kmuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('file', models.FileField(max_length=255, upload_to=know_me.models.get_media_resource_upload_path, verbose_name='file')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_resources', related_query_name='media_resource', to='know_me.Profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'media resource',
                'verbose_name_plural': 'media resources',
            },
            bases=(permission_utils.model_mixins.IsAuthenticatedMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profileitem',
            name='gallery_item',
        ),
        migrations.DeleteModel(
            name='GalleryItem',
        ),
        migrations.AddField(
            model_name='profileitem',
            name='media_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_items', related_query_name='profile_item', to='know_me.MediaResource', verbose_name='media resource'),
        ),
    ]
