# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0007_auto_20170728_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kmuser',
            options={'verbose_name': 'Know Me user', 'verbose_name_plural': 'Know Me users'},
        ),
    ]
