# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0007_listentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list_content', to='know_me.ProfileItem', verbose_name='profile item')),
            ],
            options={
                'verbose_name_plural': 'profile item lists',
                'verbose_name': 'profile item list',
            },
        ),
        migrations.AlterModelOptions(
            name='listentry',
            options={'verbose_name': 'profile item list entry', 'verbose_name_plural': 'profile item list entry'},
        ),
        migrations.RemoveField(
            model_name='listentry',
            name='profile_item',
        ),
        migrations.AddField(
            model_name='listentry',
            name='list_content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entries', related_query_name='entry', to='know_me.ListContent', verbose_name='profile item list'),
            preserve_default=False,
        ),
    ]
