# Generated by Django 2.2b1 on 2019-03-07 20:34
import hashlib

from django.db import migrations, models


def populate_receipt_hash(apps, _):
    """
    Populate the receipt data hash of existing apple subscription data
    instances.
    """
    SubscriptionAppleData = apps.get_model("know_me", "SubscriptionAppleData")
    for apple_subscription in SubscriptionAppleData.objects.all():
        data_hash = hashlib.sha256(apple_subscription.receipt_data.encode())
        apple_subscription.receipt_data_hash = data_hash.hexdigest()
        apple_subscription.save()


class Migration(migrations.Migration):

    dependencies = [("know_me", "0008_subscriptionappledata_expiration_time")]

    operations = [
        migrations.AddField(
            model_name="subscriptionappledata",
            name="receipt_data_hash",
            field=models.CharField(
                help_text="The hash of the receipt data.",
                max_length=64,
                null=True,
                verbose_name="receipt data hash",
            ),
        ),
        migrations.RunPython(
            code=populate_receipt_hash, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="subscriptionappledata",
            name="receipt_data_hash",
            field=models.CharField(
                help_text="The hash of the receipt data.",
                max_length=64,
                unique=True,
                verbose_name="receipt data hash",
            ),
        ),
    ]
