# Generated by Django 2.2 on 2019-04-29 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import permission_utils.model_mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [("know_me", "0010_subscriptionappledata_latest_receipt")]

    operations = [
        migrations.CreateModel(
            name="AppleReceipt",
            fields=[
                (
                    "expiration_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The expiration time of the most recent transaction associated with the receipt.",
                        verbose_name="expiration time",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="A unique identifier for the receipt.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_data",
                    models.TextField(
                        help_text="The base64 encoded data used to identify the receipt with Apple.",
                        verbose_name="receipt data",
                    ),
                ),
                (
                    "receipt_data_hash",
                    models.CharField(
                        help_text="The SHA256 hash of the receipt data.",
                        max_length=64,
                        unique=True,
                        verbose_name="receipt data hash",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time that the Apple receipt was initially uploaded.",
                        verbose_name="creation time",
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time of the receipt's last update.",
                        verbose_name="last update time",
                    ),
                ),
                (
                    "transaction_id",
                    models.PositiveIntegerField(
                        help_text="The ID of the original transaction from the receipt.",
                        unique=True,
                        verbose_name="original transaction ID",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        help_text="The Know Me subscription the receipt belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apple_receipt",
                        to="know_me.Subscription",
                        verbose_name="subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apple receipt",
                "verbose_name_plural": "Apple receipts",
                "ordering": ("time_created",),
            },
            bases=(
                permission_utils.model_mixins.IsAuthenticatedMixin,
                models.Model,
            ),
        )
    ]
