# Generated by Django 2.2.1 on 2019-05-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("know_me", "0012_applereceipt_transactionid_string")]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_legacy_subscription",
            field=models.BooleanField(
                default=False,
                help_text="A boolean indicating if the user has an active subscription due to them being a legacy user.",
                verbose_name="is legacy subscription",
            ),
        )
    ]
