# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0012_emergencyitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileitem',
            name='media_resource',
        ),
    ]
