# Generated by Django 2.2 on 2019-05-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("know_me", "0013_subscription_has_legacy_subscription")]

    operations = [
        migrations.RemoveField(
            model_name="applereceipt", name="receipt_data_hash"
        )
    ]
