# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0013_remove_profileitem_media_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list_content', to='know_me.ProfileItem', verbose_name='profile item')),
            ],
            options={
                'verbose_name': 'profile item list content',
                'verbose_name_plural': 'profile item list content',
            },
        ),
    ]
