# Generated by Django 2.2 on 2019-05-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("know_me", "0014_remove_applereceipt_receipt_data_hash")]

    operations = [migrations.DeleteModel(name="SubscriptionAppleData")]
