# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0015_listentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mediaresource',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profilegroup',
            name='profile',
        ),
        migrations.AddField(
            model_name='mediaresource',
            name='km_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_resources', related_query_name='media_resource', to='know_me.KMUser', verbose_name='km_user'),
        ),
        migrations.AddField(
            model_name='profilegroup',
            name='km_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', related_query_name='group', to='know_me.KMUser', verbose_name='know me user'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
