# Generated by Django 2.2.1 on 2020-06-03 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("know_me", "0015_delete_subscriptionappledata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderEmailSubscriber",
            fields=[
                ("is_subscribed", models.BooleanField(default=True)),
                (
                    "subscription_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user who has subscribed to reminder emails.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_email_subscriber",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "reminder email subscriber",
                "verbose_name_plural": "reminder email subscribers",
            },
        )
    ]
