# Generated by Django 3.0.8 on 2020-08-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("know_me", "0016_reminderemailsubscriber")]

    operations = [
        migrations.CreateModel(
            name="ReminderEmailLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time the reminder emails were sent",
                        verbose_name="sent at",
                    ),
                ),
                (
                    "schedule_frequency",
                    models.CharField(
                        default="Weekly",
                        help_text="The frequency in which the reminder emails are sheduled to send.",
                        max_length=12,
                        verbose_name="subscriber count",
                    ),
                ),
                (
                    "subscriber_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of emails being sent to users.",
                        verbose_name="suscriber count",
                    ),
                ),
            ],
        )
    ]
