# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0017_profile_group_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletopic',
            name='topic_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'text topic'), (4, 'visual topic')], verbose_name='topic type'),
        ),
    ]
