# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import permission_utils.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0018_dropcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('relation', models.TextField(max_length=255, verbose_name='relation')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('alt_phone_number', models.CharField(blank=True, max_length=15, verbose_name='alternate phone number')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('km_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', related_query_name='emergency_contact', to='know_me.KMUser', verbose_name='know me user')),
            ],
            options={
                'verbose_name': 'emergency contact',
                'verbose_name_plural': 'emergency contact',
            },
            bases=(permission_utils.model_mixins.IsAuthenticatedMixin, models.Model),
        ),
    ]
