# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 21:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0019_emergencycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='alt_phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter valid phone number', regex='^1?\\d{9,15}$')], verbose_name='alternate phone number'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter valid phone number', regex='^1?\\d{9,15}$')], verbose_name='phone number'),
        ),
    ]
