# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import permission_utils.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('know_me', '0020_alter_emergencycontact_phone_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMUserAccessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, help_text='The KMUser has accepted the access.', verbose_name='is accepted')),
                ('can_read_everywhere', models.BooleanField(default=False, help_text='The user has can read everywhere access.', verbose_name='can read everywhere')),
                ('can_write_everywhere', models.BooleanField(default=False, help_text='The user has write everywhere access.', verbose_name='can write everywhere')),
                ('km_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='km_user_accessors', related_query_name='km_user_accessor', to='know_me.KMUser', verbose_name='Know Me user')),
                ('user_with_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='km_user_accessors', related_query_name='km_user_accessor', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Know Me user accessor',
                'verbose_name_plural': 'Know Me user accessors',
            },
            bases=(permission_utils.model_mixins.IsAuthenticatedMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='kmuseraccessor',
            unique_together=set([('km_user', 'user_with_access')]),
        ),
    ]
