# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0023_setfieldsnonnullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmuseraccessor',
            name='can_read_everywhere',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False, help_text='The profile is by default public.', verbose_name='is private'),
        ),
    ]
