# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0024_profile_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(max_length=255, verbose_name='relation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private profiles are only visable to admin.', verbose_name='is private'),
        ),
    ]
