# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0025_change_emergency_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmuseraccessor',
            name='can_write_everywhere',
        ),
        migrations.AddField(
            model_name='kmuseraccessor',
            name='can_write',
            field=models.BooleanField(default=False, help_text='Users with write access can make changes to the profiles they are invited to.', verbose_name='can write'),
        ),
        migrations.AddField(
            model_name='kmuseraccessor',
            name='has_private_profile_access',
            field=models.BooleanField(default=False, verbose_name='has private profile access'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private profiles are only visable to admin.', verbose_name='is private'),
        ),
    ]
