# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 00:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0027_delete_profileaccessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmuseraccessor',
            name='email',
            field=models.EmailField(help_text='The email address used to invite the user.', max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='kmuseraccessor',
            name='user_with_access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='km_user_accessors', related_query_name='km_user_accessor', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
