# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0028_kmuseraccessor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaResourceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category.', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(help_text="A URL-safe version of the category's name.", unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'media resource category',
                'verbose_name_plural': 'media resource categories',
            },
        ),
    ]
