# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0028_kmuseraccessor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaResourceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The category's name.", max_length=255, verbose_name='name')),
                ('km_user', models.ForeignKey(help_text='The Know Me user who owns the category.', on_delete=django.db.models.deletion.CASCADE, related_name='media_resource_categories', related_query_name='media_resource_category', to='know_me.KMUser', verbose_name='media resource category')),
            ],
            options={
                'verbose_name': 'media resource category',
                'verbose_name_plural': 'media resource categories',
            },
        ),
    ]
