# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0030_mediaresource_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_default',
        ),
    ]
