# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0031_remove_profile_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmuseraccessor',
            name='email',
            field=models.EmailField(help_text='The email address used to invite the user.', max_length=254, verbose_name='email'),
        ),
    ]
