# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 20:54
from __future__ import unicode_literals

from django.db import migrations, models


def populate_order(apps, schema_editor):

    KMUser = apps.get_model('know_me', 'KMUser')
    for km_user in KMUser.objects.all():
        for index, profile in enumerate(km_user.profiles.all()):
            profile.order = index
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0032_accessor_email_non_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.IntegerField(null=True, verbose_name='order'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('km_user', 'order')]),
        ),
        migrations.RunPython(populate_order, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='order',
            field=models.IntegerField(verbose_name='order'),
        ),
    ]
