# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0032_accessor_email_non_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='km_user',
        ),
        migrations.RemoveField(
            model_name='emergencyitem',
            name='km_user',
        ),
        migrations.RemoveField(
            model_name='emergencyitem',
            name='media_resource',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='EmergencyItem',
        ),
    ]
